[project]
name = "youtube-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytube>=15.0.0",
    "streamlit>=1.48.0",
    "yt-dlp>=2025.7.21",
]
